version: '3.8'

volumes:
  qsr_log:
services:
  qsr:
    container_name: qsr
    expose:
      - 28458
    ports:
      - "28458:8888"
    volumes:
      - "qsr_log:/var/log"
    image: "lotusk08/lottery:v0.3"
    restart: always
